### PR TITLE
open in newtab for links in lets begin

### PR DESCRIPTION
**Pull request by Amrutha1101**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed # (issue) (e.g. Fixed #10)

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [ ] I have squashed my commits
- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
@shriya030  I've successfully made changes  issue #17  resolved

### CODE REVIEW

**Review by aj3011 — CHANGES_REQUESTED** [review]
Please check it again! It's not working.

**Comment by Amrutha1101** [comment]
what is not working..?

**Comment by Amrutha1101** [comment]
Screenshot (90)

**Comment by Amrutha1101** [comment]
The links are opening in new tab when clicked @aj3011.

**Comment by Amrutha1101** [comment]
please comment on the specific line where i need to change..

**Review by shriya030 — APPROVED** [review]

**Comment by aj3011** [comment]
> please comment on the specific line where i need to change..

I was expecting links on other things too! But that's okay!
Logically it's correct.

**Review by aj3011 — APPROVED** [review]

**Pull request merged**
