### PR TITLE
updated 3 more languages material

### PR DESCRIPTION
**Pull request by ritik-vashist**
Fixed # 27

Added 3 more languages in language section i.e- java,c,javascript

@shriya030 ma'am i  request you to review my work.

### CODE REVIEW

**Review by aj3011 — CHANGES_REQUESTED** [review]
There's a lot of good content available for these languages. Add more content.

**Comment by ritik-vashist** [comment]
@aj3011, @shriya030 could you tell me approx quantity of the resources in each section? 
As I tried to add a quality resources in each section . 
Most of the resources which I used have been used by me and my classmates. 
It would be helpful if you give any number so i will work accordingly.

**Comment by shriya030** [comment]
> @aj3011, @shriya030 could you tell me approx quantity of the resources in each section?
> As I tried to add a quality resources in each section .
> Most of the resources which I used have been used by me and my classmates.
> It would be helpful if you give any number so i will work accordingly.

Maximum 6 resources can be added under each section
Like you have added 2-3 in some of them. Explore a little and try to add at least 4 if there are some good ones.

**Comment by ritik-vashist** [comment]
@shriya030 Ma'am i added the resources as suggested by.
I request you to please review my work.

**Review by shriya030 — APPROVED** [review]

**Comment by ritik-vashist** [comment]
@aj3011  sir I request you to please review my work.

**Comment by ritik-vashist** [comment]
@shriya030 ma'am  @aj3011  sir I request you to give labels according to LGMSOC rules.

**Review by aj3011 — APPROVED** [review]

**Pull request merged**
