### PR TITLE
Page transitions

### LINKED ISSUE #79: Page transitions and animations between routes
### **Feature request**:

A clear and concise description of the feature.
Implementation of a page transitions and animations between react-routes. The preloader will be limited just to the initial loading of the home page.
### **Is your feature request related to a problem? Please describe. (optional)**:

A clear and concise description of what the problem is.

### **Describe the solution you'd like**:

I would like to add sleek transitions between routes using react framer-motion library
### **Describe how this feature will be useful to our readers**:

A clear and concise description of how this feature will be useful for our other readers.
This feature will ensure a much more smooth experience to the viewer.
### **Additional context:**

<hr/>

**Note:**

- If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by Srijan1878**
# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed # (issue) (e.g. Fixed #10)
Fixed #79 
## Type of change
Added a feature
Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [ ] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by khareyash05** [comment]
@Srijan1878 Please share a video of the changes

**Comment by Srijan1878** [comment]
@khareyash05 Okay

**Comment by Srijan1878** [comment]
https://user-images.githubusercontent.com/80585719/124344968-6d2af600-dbf3-11eb-93eb-2c394d181587.mp4

Here's the video. There are transitions for other routes too. I just kept the video short.

**Comment by khareyash05** [comment]
LGTM @Srijan1878

**Comment by shriya030** [comment]
@Srijan1878 Good work🎉

**Review by shriya030 — APPROVED** [review]

**Pull request merged**
