### PR TITLE
fix about me bug

### PR DESCRIPTION
**Pull request by deeola**
# Description
 #85 
Redirection to About section from navbar while on other pages does not work.

How i solved the problem and dependencies

npm install --save react-router-hash-link

import { HashLink } from 'react-router-hash-link';

<HashLink to="/#ab">About</HashLink> was added into the <Nav.Link>

Fixed #85 

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by abhijeet-chatterjee** [comment]
@deeola Can you show a small video showing issue being fixed

**Comment by deeola** [comment]
@abhijeet007rocks8 the code or the solution?

**Comment by abhijeet-chatterjee** [comment]
working demo on localhost

**Comment by deeola** [comment]
https://user-images.githubusercontent.com/71495600/125572820-e192ef9f-cfc2-4b5a-98d1-782b7b249886.mp4

Hello, that is the link to the video

**Review by shriya030 — APPROVED** [review]
Good work!

**Review by aj3011 — APPROVED** [review]

**Pull request merged**
